// package workergo
// connects to Kafka, reads the JSON payload, and initializes a connection to Temporal.
package main

import (
	"context"
	"encoding/json"
	"log"
	"os"

	"github.com/segmentio/kafka-go"
	"go.temporal.io/sdk/client"
)

// UploadEvent matches the JSON payload generated by the Ruby API
type UploadEvent struct {
	FileID    string `json:"file_id"`
	S3URI     string `json:"s3_uri"`
	Timestamp string `json:"timestamp"`
	Status    string `json:"status"`
}

func main() {
	// 1. Initialize Temporal Client
	temporalHost := os.Getenv("TEMPORAL_HOST_PORT")
	if temporalHost == "" {
		temporalHost = "localhost:7233"
	}

	c, err := client.Dial(client.Options{
		HostPort: temporalHost,
	})
	if err != nil {
		log.Fatalln("Unable to create Temporal client", err)
	}
	defer c.Close()
	log.Println("Connected to Temporal Cluster")

	// 2. Initialize Kafka Reader
	kafkaBroker := os.Getenv("KAFKA_BROKERS")
	if kafkaBroker == "" {
		kafkaBroker = "localhost:9092"
	}

	reader := kafka.NewReader(kafka.ReaderConfig{
		Brokers:  []string{kafkaBroker},
		GroupID:  "go-temporal-bridge-group",
		Topic:    "media.uploaded",
		MinBytes: 10e3, // 10KB
		MaxBytes: 10e6, // 10MB
	})
	defer reader.Close()
	log.Println("Listening for events on Kafka topic: media.uploaded")

	// 3. Consume Loop
	for {
		m, err := reader.ReadMessage(context.Background())
		if err != nil {
			log.Printf("Kafka read error: %v", err)
			continue
		}

		var event UploadEvent
		if err := json.Unmarshal(m.Value, &event); err != nil {
			log.Printf("Failed to unmarshal JSON: %v", err)
			continue
		}

		log.Printf("Received event for FileID: %s | S3 URI: %s", event.FileID, event.S3URI)

		// 4. Trigger Temporal Workflow (Implementation in Phase 4)
		// We use the FileID as the WorkflowID to ensure idempotency.
		// If Kafka re-delivers the message, Temporal will ignore the duplicate request.
		options := client.StartWorkflowOptions{
			ID:        "media-pipeline-" + event.FileID,
			TaskQueue: "MEDIA_PROCESSING_TASK_QUEUE",
		}

		// Note: "MediaProcessingWorkflow" is a string reference. We will write the actual 
		// workflow logic in Phase 4.
		we, err := c.ExecuteWorkflow(context.Background(), options, "MediaProcessingWorkflow", event)
		if err != nil {
			log.Printf("Unable to execute workflow for %s: %v", event.FileID, err)
		} else {
			log.Printf("Started workflow. ID: %s, RunID: %s", we.GetID(), we.GetRunID())
		}
	}
}